name: Ola Hallengren FUll_Backup
on:
  workflow_dispatch:
  
jobs:
  ola-backup:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ola Hallengren Backup
        shell: powershell
        run: |
          $repo = wsl wslpath '${{ github.workspace }}'

          Write-Host "Repository: $repo"

          wsl bash -lc "cd '$repo' && ansible-playbook -i ansible/inventory.ini ansible/ola-Full_backup.yml"