name: Ola Hallengren Backup

on:
  workflow_dispatch:

jobs:
  ola-backup:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Ansible
        shell: bash
        run: |
          ansible --version

      - name: Check inventory
        shell: bash
        run: |
          ansible-inventory -i ansible/inventory.ini --graph

      - name: Test Windows connectivity
        shell: bash
        run: |
          ansible -i ansible/inventory.ini windows -m ansible.windows.win_ping

      - name: Run Ola Hallengren backup
        shell: bash
        run: |
          ansible-playbook \
            -i ansible/inventory.ini \
            ansible/test.yml
