name: Ola Hallengren LOG_Backup
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  
jobs:
  ola-LOG_backup:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ola Hallengren Backup
        shell: powershell
        run: |
          $repo = wsl wslpath '${{ github.workspace }}'

          Write-Host "Repository: $repo"

          wsl bash -lc "cd '$repo' && ansible-playbook -i ansible/inventory.ini ansible/ola-Log_backup.yml"