name: Ola Hallengren LOG_Backup
on:
  workflow_dispatch:
    inputs:
      BackupType:
        description: 'Enter the backup type (FULL, DIFF, LOG)'
        required: true
        type: choice
        default: LOG
        options:
          - FULL
          - DIFF
          - LOG

jobs:
  ola-LOG_backup:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ola Hallengren Backup
        shell: powershell
        run: |
          $repo = wsl.exe -d Ubuntu -- wslpath 'C:\Users\ADMINISTRATOR\actions-runner\_work\SQL-Backup\SQL-Backup'
          Write-Host "Repository: $repo"
          wsl bash -lc "cd '$repo' && ansible-playbook -i ansible/inventory.ini ansible/ola-Log_backup.yml"
